encode_type="UTF-8"
dictionary_tha="/home/nokk_is/PycharmProjects/MTProjects/MT-DataProcessing/dict/v2/MasterDict.TH.tok"
dictionary_tab="/home/nokk_is/PycharmProjects/MTProjects/MT-DataProcessing/dict/v2/EN-TH.dic"
# dictionary_tab='/home/nokk_is/PycharmProjects/MTProjects/MT-DataProcessing/data/temp/complete/v3/ThaiSubtitle-Crawling.tab'
dictionary_hun="/home/nokk_is/PycharmProjects/MTProjects/MT-DataProcessing/dict/v2/HUN.EN-TH.dic"
JOIN_MSEC_DIFF=0.30
FMT = '%H:%M:%S.%f';
DIFF_START_TRESHOLD = '00:00:00.60';
DIFF_START_DUMMAY = '00:00:10.60';